### ISSUE TITLE
Разработать API для поиска товаров по тексту запроса

### ISSUE THREAD

**Issue by oagafonov** [Java-Java-Bootcamp/marketplace#5]
```yaml
GET /product-offers?text={text}

response: List Of ProductOffer

ProductOffer:
  product:
    category: text
    model: text
    manufacturer: text
    description: text
    rate: numeric
  store:
     name: text
     rate: numeric
  available: numeric
```
